# Generated by Django 4.1.7 on 2023-04-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('stage', models.CharField(choices=[('S', 'Seed'), ('G', 'Germination'), ('F', 'Flowering'), ('P', 'Pollination')], default='S', max_length=1)),
            ],
        ),
    ]
